import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f6faff",
        "surface-dim": "#d2dbe4",
        "surface-bright": "#f6faff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ecf5fe",
        "surface-container": "#e6eff8",
        "surface-container-high": "#e0e9f2",
        "surface-container-highest": "#dbe4ed",
        "surface-variant": "#dbe4ed",
        "on-surface": "#141d23",
        "on-surface-variant": "#5b3f43",
        "inverse-surface": "#293138",
        "inverse-on-surface": "#e9f2fb",
        outline: "#8f6f73",
        "outline-variant": "#e4bdc2",
        "surface-tint": "#bc004b",
        primary: "#b80049",
        "on-primary": "#ffffff",
        "primary-container": "#e2165f",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb2be",
        secondary: "#5f5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2dfde",
        "on-secondary-container": "#636262",
        tertiary: "#5a5c5d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#737576",
        "on-tertiary-container": "#fcfdfe",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffd9de",
        "primary-fixed-dim": "#ffb2be",
        "on-primary-fixed": "#400014",
        "on-primary-fixed-variant": "#900038",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "tertiary-fixed": "#e1e3e4",
        "tertiary-fixed-dim": "#c5c7c8",
        "on-tertiary-fixed": "#191c1d",
        "on-tertiary-fixed-variant": "#454748",
        background: "#f6faff",
        "on-background": "#141d23",
        success: "#10b981",
        warning: "#f59e0b",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      maxWidth: {
        container: "1700px",
        "container-max": "1700px",
      },
      boxShadow: {
        soft: "0px 10px 30px rgba(0,0,0,0.04)",
        "soft-lg": "0px 16px 40px rgba(0,0,0,0.08)",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
    },
  },
  plugins: [],
};

export default config;
