import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#636262",
        background: "#f5faff",
        "surface-bright": "#f5faff",
        "tertiary-fixed-dim": "#c5c6c7",
        "on-tertiary-fixed-variant": "#454748",
        "primary-fixed-dim": "#ffb2be",
        "tertiary-fixed": "#e2e2e3",
        "surface-ice": "#f6faff",
        tertiary: "#424546",
        "on-primary-fixed-variant": "#900038",
        "surface-container-highest": "#dae4ec",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#e9f2fa",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-surface": "#293238",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#141d23",
        surface: "#f5faff",
        "success-container": "#e2dfde",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#ffb2be",
        "outline-variant": "#e2bec2",
        "on-tertiary-fixed": "#1a1c1d",
        "on-secondary-fixed-variant": "#474647",
        "surface-container": "#e6eff8",
        "surface-dim": "#d2dbe4",
        "secondary-fixed": "#e5e2e1",
        primary: "#8c0036",
        "surface-variant": "#dae4ec",
        secondary: "#5f5e5e",
        "on-surface": "#141d23",
        "surface-container-low": "#ebf5fd",
        "on-tertiary-container": "#d4d4d5",
        "tertiary-container": "#5a5c5d",
        "secondary-container": "#e2dfdf",
        "surface-container-lowest": "#ffffff",
        "active-glow": "#e2165f",
        outline: "#8e6f73",
        "on-primary-fixed": "#400014",
        "surface-tint": "#bb064b",
        "on-surface-muted": "#5b3f43",
        "on-error-container": "#93000a",
        "on-primary-container": "#ffc6ce",
        "secondary-fixed-dim": "#c8c6c6",
        "primary-container": "#b80049",
        "on-surface-variant": "#5a4044",
        "on-secondary-fixed": "#1c1b1c",
        "primary-fixed": "#ffd9de",
        "surface-container-high": "#e0e9f2",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "container-max": "1280px",
        gutter: "24px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "title-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
