-- Seed 30 realistic parcels into the parcels Supabase project
-- Run this against your PARCELS_SUPABASE_URL database

INSERT INTO public.parcels (
  tracking_number,
  customer_name,
  pickup_location,
  dropoff_location,
  weight_kg,
  status,
  courier,
  priority,
  pickup_address,
  delivery_address,
  created_at
) VALUES
  ('TRK001', 'John Smith', 'Central Warehouse', '123 Oak St, Downtown', 2.5, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '123 Oak Street, Downtown District', NOW()),
  ('TRK002', 'Sarah Johnson', 'Central Warehouse', '456 Maple Ave, Midtown', 1.8, 'pending', 'FastEx', 'High', 'Central Warehouse, 999 Industrial Ave', '456 Maple Avenue, Midtown Plaza', NOW()),
  ('TRK003', 'Michael Chen', 'Central Warehouse', '789 Pine Rd, North Side', 3.2, 'pending', 'QuickDeliver', 'Normal', 'Central Warehouse, 999 Industrial Ave', '789 Pine Road, North Side Heights', NOW()),
  ('TRK004', 'Emma Davis', 'Central Warehouse', '321 Elm Blvd, East End', 0.9, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '321 Elm Boulevard, East End Market', NOW()),
  ('TRK005', 'Robert Wilson', 'Central Warehouse', '654 Birch Ln, West Gate', 4.1, 'pending', 'QuickDeliver', 'Normal', 'Central Warehouse, 999 Industrial Ave', '654 Birch Lane, West Gate Complex', NOW()),
  ('TRK006', 'Lisa Anderson', 'Central Warehouse', '987 Cedar St, South Park', 2.3, 'pending', 'FastEx', 'High', 'Central Warehouse, 999 Industrial Ave', '987 Cedar Street, South Park Shopping', NOW()),
  ('TRK007', 'David Martinez', 'Central Warehouse', '147 Spruce Ave, Harbor', 1.5, 'pending', 'QuickDeliver', 'Normal', 'Central Warehouse, 999 Industrial Ave', '147 Spruce Avenue, Harbor Front District', NOW()),
  ('TRK008', 'Jennifer Taylor', 'Central Warehouse', '258 Walnut Rd, Central', 2.7, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '258 Walnut Road, Central Hub', NOW()),
  ('TRK009', 'Christopher Brown', 'Central Warehouse', '369 Ash Blvd, Tech Park', 1.2, 'pending', 'QuickDeliver', 'High', 'Central Warehouse, 999 Industrial Ave', '369 Ash Boulevard, Tech Park Building A', NOW()),
  ('TRK010', 'Amanda White', 'Central Warehouse', '741 Hickory Ln, Riverside', 3.6, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '741 Hickory Lane, Riverside Complex', NOW()),
  ('TRK011', 'Daniel Harris', 'Central Warehouse', '852 Chestnut St, Industrial', 5.2, 'pending', 'QuickDeliver', 'Normal', 'Central Warehouse, 999 Industrial Ave', '852 Chestnut Street, Industrial Zone', NOW()),
  ('TRK012', 'Michelle Garcia', 'Central Warehouse', '963 Poplar Ave, Gateway', 1.1, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '963 Poplar Avenue, Gateway Station', NOW()),
  ('TRK013', 'James Robinson', 'Central Warehouse', '159 Sycamore Rd, Summit', 2.9, 'pending', 'QuickDeliver', 'High', 'Central Warehouse, 999 Industrial Ave', '159 Sycamore Road, Summit Heights', NOW()),
  ('TRK014', 'Karen Lee', 'Central Warehouse', '357 Dogwood Blvd, Valley', 0.8, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '357 Dogwood Boulevard, Valley Floor', NOW()),
  ('TRK015', 'Ryan Martinez', 'Central Warehouse', '456 Mulberry St, Ridge', 3.4, 'pending', 'QuickDeliver', 'Normal', 'Central Warehouse, 999 Industrial Ave', '456 Mulberry Street, Ridge View', NOW()),
  ('TRK016', 'Patricia Clark', 'Central Warehouse', '567 Magnolia Ln, Forest', 2.1, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '567 Magnolia Lane, Forest Park Area', NOW()),
  ('TRK017', 'Joseph Rodriguez', 'Central Warehouse', '678 Laurel Ave, Grove', 4.5, 'pending', 'QuickDeliver', 'High', 'Central Warehouse, 999 Industrial Ave', '678 Laurel Avenue, Grove Shopping Center', NOW()),
  ('TRK018', 'Linda Thompson', 'Central Warehouse', '789 Hazel Rd, Meadow', 1.6, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '789 Hazel Road, Meadow View District', NOW()),
  ('TRK019', 'Mark Jackson', 'Central Warehouse', '891 Willow St, Strand', 2.8, 'pending', 'QuickDeliver', 'Normal', 'Central Warehouse, 999 Industrial Ave', '891 Willow Street, Strand Beach Area', NOW()),
  ('TRK020', 'Susan Martin', 'Central Warehouse', '912 Rowan Blvd, Cliff', 3.3, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '912 Rowan Boulevard, Cliff Edge Tower', NOW()),
  ('TRK021', 'Steven Perez', 'Central Warehouse', '123 Alder Ln, Platform', 1.4, 'pending', 'QuickDeliver', 'High', 'Central Warehouse, 999 Industrial Ave', '123 Alder Lane, Platform Station', NOW()),
  ('TRK022', 'Betty Moore', 'Central Warehouse', '234 Fir Ave, Junction', 2.6, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '234 Fir Avenue, Junction Point Commercial', NOW()),
  ('TRK023', 'Paul Thomas', 'Central Warehouse', '345 Larch Rd, Terminal', 0.7, 'pending', 'QuickDeliver', 'Normal', 'Central Warehouse, 999 Industrial Ave', '345 Larch Road, Terminal Station', NOW()),
  ('TRK024', 'Nancy Jackson', 'Central Warehouse', '456 Basswood St, Depot', 3.9, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '456 Basswood Street, Depot Center', NOW()),
  ('TRK025', 'George White', 'Central Warehouse', '567 Cottonwood Blvd, Base', 2.2, 'pending', 'QuickDeliver', 'High', 'Central Warehouse, 999 Industrial Ave', '567 Cottonwood Boulevard, Base Camp', NOW()),
  ('TRK026', 'Martha Harris', 'Central Warehouse', '678 Hackberry Ln, Point', 4.3, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '678 Hackberry Lane, Point Ridge', NOW()),
  ('TRK027', 'Edward Martin', 'Central Warehouse', '789 Sandalwood Ave, Cross', 1.3, 'pending', 'QuickDeliver', 'Normal', 'Central Warehouse, 999 Industrial Ave', '789 Sandalwood Avenue, Crossroads Mall', NOW()),
  ('TRK028', 'Dorothy Harris', 'Central Warehouse', '891 Redwood Rd, Crown', 2.4, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '891 Redwood Road, Crown Heights', NOW()),
  ('TRK029', 'Charles Thompson', 'Central Warehouse', '912 Ebony St, Crest', 3.7, 'pending', 'QuickDeliver', 'High', 'Central Warehouse, 999 Industrial Ave', '912 Ebony Street, Crest View Plaza', NOW()),
  ('TRK030', 'Joyce Garcia', 'Central Warehouse', '123 Mahogany Ln, Summit', 1.9, 'pending', 'FastEx', 'Normal', 'Central Warehouse, 999 Industrial Ave', '123 Mahogany Lane, Summit Office Tower', NOW());
